### PR TITLE
socials, programs, more bootstrap stuff, events, and RESPONSIVENESS!!!!!!!!!

### PR DESCRIPTION
**Pull request by Poundcaked**
bottom bar edited 
programs boxes added (will fix later, just setting up)
template images, change it  by going to the program's div and changing the image
bootstrap stuff replaceing other stuff (way better)
bootstrap grid added
things now scale (and dont exit the screen)

### CODE REVIEW

**Comment by mapoztate** [comment]
Have you taken into account scaling? It scales outside of the footer box at different resolutions. Add some margins around the footer so that way the text doesn't go out like that.

**Comment by Poundcaked** [comment]
> Have you taken into account scaling? It scales outside of the footer box at different resolutions. Add some margins around the footer so that way the text doesn't go out like that.

alright, ill do that

**Comment by mapoztate** [comment]
I haven't added the donation button to Figma because I was still wondering how I wanted to execute it. If we do end up having the navigation links aligned to the left (as it is right now), I think the donation button would fit well on the right side of the navbar. The slideshow's fine but let's avoid working on other pages until we have the landing page done. I'll have to draft the other ones in terms of how it should look (need to consult a friend abt UI design).

**Comment by Poundcaked** [comment]
> I haven't added the donation button to Figma because I was still wondering how I wanted to execute it. If we do end up having the navigation links aligned to the left (as it is right now), I think the donation button would fit well on the right side of the navbar. The slideshow's fine but let's avoid working on other pages until we have the landing page done. I'll have to draft the other ones in terms of how it should look (need to consult a friend abt UI design).

Sounds good! Landing page is basically complete. Just needs more text and images ( and obviously the scaling issues need to be fixed ), tell me if anything needs has changed in the Figma file and I'll check it out.

**Comment by mapoztate** [comment]
I noticed that you ended up using an image for the little aesthetic pattern at the bottom. See if you can use the native CSS property instead so that way we can make adjustments easily if we want to alter it.

**Comment by Poundcaked** [comment]
> I noticed that you ended up using an image for the little aesthetic pattern at the bottom. See if you can use the native CSS property instead so that way we can make adjustments easily if we want to alter it.

Alright, I'm working on placing all the stuff in the bootstrap grid (rows, columns, etc) I changed the little aesthetic thing, next pull request you'll see what I mean. It's more like a triangle, though.

**Comment by mapoztate** [comment]
That's perfect - I'll check on this periodically. I revised the design on Figma a bit. Let's stick to that design strictly. And yeah, the aesthetic part is a linear gradient so its a straight design going downward rather than the circular pattern on the website, but that's fine.

**Comment by mapoztate** [comment]
Closing this up for now. Feel free to open another one.

**Pull request merged**
